import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/group_model.dart';
import '../models/message_model.dart';
import '../models/user_model.dart';

class ChatService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Stream<List<UserModel>> getUsers() {
    return _firestore.collection('users').snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => UserModel.fromDocument(doc)).toList();
    });
  }

  Stream<UserModel?> getUserStream(String uid) {
    return _firestore.collection('users').doc(uid).snapshots().map((snapshot) {
      if (snapshot.exists) {
        return UserModel.fromDocument(snapshot);
      }
      return null;
    });
  }

  Future<void> sendMessage(
      String senderId, String senderName, String receiverId, String text, MessageType type) async {
    final timestamp = DateTime.now();
    MessageModel newMessage = MessageModel(
      id: '', // Generated by Firestore
      senderId: senderId,
      senderName: senderName,
      receiverId: receiverId,
      text: text,
      type: type,
      timestamp: timestamp,
      isRead: false,
    );

    List<String> ids = [senderId, receiverId];
    ids.sort();
    String chatRoomId = ids.join('_');

    await _firestore
        .collection('chat_rooms')
        .doc(chatRoomId)
        .collection('messages')
        .add(newMessage.toMap());
        
    // Update last message in chat room for list view (optional but good for performance)
     await _firestore.collection('chat_rooms').doc(chatRoomId).set({
      'lastMessage': text,
      'lastMessageTime': timestamp.millisecondsSinceEpoch,
      'users': ids,
      'type': type.name,
    }, SetOptions(merge: true));
  }

  Stream<List<MessageModel>> getMessages(String userId, String otherUserId) {
    List<String> ids = [userId, otherUserId];
    ids.sort();
    String chatRoomId = ids.join('_');

    return _firestore
        .collection('chat_rooms')
        .doc(chatRoomId)
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => MessageModel.fromDocument(doc))
          .where((msg) => !msg.deletedBy.contains(userId))
          .toList();
    });
  }
  
  Future<void> markMessageAsRead(String chatRoomId, String messageId) async {
     await _firestore
        .collection('chat_rooms')
        .doc(chatRoomId)
        .collection('messages')
        .doc(messageId)
        .update({'isRead': true});
  }

  Future<void> updateMessage(String chatRoomId, String messageId, String newText) async {
    await _firestore
        .collection('chat_rooms')
        .doc(chatRoomId)
        .collection('messages')
        .doc(messageId)
        .update({
      'text': newText,
      'isEdited': true,
    });

    // Update last message in room if it was the last one
    await _firestore.collection('chat_rooms').doc(chatRoomId).update({
      'lastMessage': newText,
    });
  }

  Future<void> deleteMessage(String chatRoomId, String messageId, bool deleteForBoth, String currentUserId) async {
    final messageRef = _firestore.collection('chat_rooms').doc(chatRoomId).collection('messages').doc(messageId);
    
    if (deleteForBoth) {
      await messageRef.delete();
    } else {
      await messageRef.update({
        'deletedBy': FieldValue.arrayUnion([currentUserId])
      });
    }

    // Sync lastMessage in chat room
    final lastMessages = await _firestore
        .collection('chat_rooms')
        .doc(chatRoomId)
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .limit(1)
        .get();

    if (lastMessages.docs.isNotEmpty) {
      final lastMsg = MessageModel.fromDocument(lastMessages.docs.first);
      await _firestore.collection('chat_rooms').doc(chatRoomId).update({
        'lastMessage': lastMsg.text,
        'lastMessageTime': lastMsg.timestamp.millisecondsSinceEpoch,
        'lastMessageDeletedFor': lastMsg.deletedBy, // Tracks who deleted the CURRENT last message
      });
    } else {
      await _firestore.collection('chat_rooms').doc(chatRoomId).update({
        'lastMessage': '',
        'lastMessageTime': 0,
        'lastMessageDeletedFor': [],
      });
    }
  }

  // --- Group Chat Methods ---

  Future<String> createGroup(String groupName, List<String> memberIds, String creatorId) async {
    final docRef = _firestore.collection('groups').doc();
    final timestamp = DateTime.now();
    
    await docRef.set({
      'name': groupName,
      'createdBy': creatorId,
      'members': memberIds,
      'lastMessage': 'Group created',
      'lastMessageTime': timestamp.millisecondsSinceEpoch,
    });
    
    return docRef.id;
  }

  Stream<List<GroupModel>> getGroups(String userId) {
    return _firestore
        .collection('groups')
        .where('members', arrayContains: userId)
        .snapshots()
        .map((snapshot) {
      final groups = snapshot.docs.map((doc) => GroupModel.fromDocument(doc)).toList();
      groups.sort((a, b) => b.lastMessageTime.compareTo(a.lastMessageTime));
      return groups;
    });
  }

  Future<void> sendGroupMessage(String groupId, String senderId, String senderName, String text) async {
    final timestamp = DateTime.now();
    await _firestore
        .collection('groups')
        .doc(groupId)
        .collection('messages')
        .add({
      'senderId': senderId,
      'senderName': senderName,
      'text': text,
      'timestamp': timestamp.millisecondsSinceEpoch,
      'type': 'text',
    });

    await _firestore.collection('groups').doc(groupId).update({
      'lastMessage': text,
      'lastMessageTime': timestamp.millisecondsSinceEpoch,
    });
  }

  Future<void> updateGroupMessage(String groupId, String messageId, String newText) async {
    await _firestore
        .collection('groups')
        .doc(groupId)
        .collection('messages')
        .doc(messageId)
        .update({
      'text': newText,
      'isEdited': true,
    });

    await _firestore.collection('groups').doc(groupId).update({
      'lastMessage': newText,
    });
  }

  Future<void> deleteGroupMessage(String groupId, String messageId, bool deleteForBoth, String currentUserId) async {
    final messageRef = _firestore.collection('groups').doc(groupId).collection('messages').doc(messageId);
    
    if (deleteForBoth) {
      await messageRef.delete();
    } else {
      await messageRef.update({
        'deletedBy': FieldValue.arrayUnion([currentUserId])
      });
    }

    // Sync lastMessage in group
    final lastMessages = await _firestore
        .collection('groups')
        .doc(groupId)
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .limit(1)
        .get();

    if (lastMessages.docs.isNotEmpty) {
      final lastData = lastMessages.docs.first.data();
      await _firestore.collection('groups').doc(groupId).update({
        'lastMessage': lastData['text'] ?? '',
        'lastMessageTime': lastData['timestamp'] ?? 0,
      });
    } else {
      await _firestore.collection('groups').doc(groupId).update({
        'lastMessage': '',
        'lastMessageTime': 0,
      });
    }
  }

  Stream<List<MessageModel>> getGroupMessages(String groupId, String userId) {
    return _firestore
        .collection('groups')
        .doc(groupId)
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) {
        final data = doc.data();
        return MessageModel(
          id: doc.id,
          senderId: data['senderId'] ?? '',
          senderName: data['senderName'] ?? '',
          receiverId: '', // Groups use groupId
          text: data['text'] ?? '',
          type: MessageType.text,
          timestamp: DateTime.fromMillisecondsSinceEpoch(data['timestamp'] ?? 0),
          isRead: true, // simplified for groups
          isEdited: data['isEdited'] ?? false,
          deletedBy: List<String>.from(data['deletedBy'] ?? []),
        );
      }).where((msg) => !msg.deletedBy.contains(userId)).toList();
    });
  }
  
  Stream<List<Map<String, dynamic>>> getActiveChats(String userId) {
    return _firestore
        .collection('chat_rooms')
        .where('users', arrayContains: userId)
        .snapshots()
        .map((snapshot) {
      List<Map<String, dynamic>> rooms = [];

      for (var doc in snapshot.docs) {
        final data = doc.data();
        List<dynamic> users = data['users'];
        String? partnerId = users.firstWhere((id) => id != userId, orElse: () => null) as String?;

        if (partnerId != null) {
          // Check if lastMessage was deleted specifically for this user
          final deletedFor = List<String>.from(data['lastMessageDeletedFor'] ?? []);
          if (!deletedFor.contains(userId)) {
            rooms.add({
              'partnerId': partnerId,
              'lastMessageTime': data['lastMessageTime'] ?? 0,
              'lastMessage': data['lastMessage'] ?? '',
            });
          }
        }
      }
      // ... same sorting ...

      // Sort by time
      rooms.sort((a, b) {
        final timeA = a['lastMessageTime'];
        final timeB = b['lastMessageTime'];
        int valA = timeA is int ? timeA : (timeA is Timestamp ? timeA.millisecondsSinceEpoch : 0);
        int valB = timeB is int ? timeB : (timeB is Timestamp ? timeB.millisecondsSinceEpoch : 0);
        return valB.compareTo(valA);
      });

      return rooms;
    });
  }

  // Helper to get chat room ID
  static String getChatRoomId(String user1, String user2) {
    List<String> ids = [user1, user2];
    ids.sort();
    return ids.join('_');
  }

  // Get unread count for a specific chat room
  Stream<int> getUnreadCount(String chatRoomId, String currentUserId) {
    return _firestore
        .collection('chat_rooms')
        .doc(chatRoomId)
        .collection('messages')
        .where('receiverId', isEqualTo: currentUserId)
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  // Mark all messages in a chat room as read
  Future<void> markMessagesAsRead(String chatRoomId, String currentUserId) async {
    final unreadMessages = await _firestore
        .collection('chat_rooms')
        .doc(chatRoomId)
        .collection('messages')
        .where('receiverId', isEqualTo: currentUserId)
        .where('isRead', isEqualTo: false)
        .get();

    final batch = _firestore.batch();
    for (var doc in unreadMessages.docs) {
      batch.update(doc.reference, {'isRead': true});
    }
    await batch.commit();
  }
}
