// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcV0Dp6MjRvfN9f0P-LNoqoawkRP_ivs4',
    appId: '1:687345271480:web:03f5e3a10c2c78ebbf2a4d',
    messagingSenderId: '687345271480',
    projectId: 'prochat-1d511',
    authDomain: 'prochat-1d511.firebaseapp.com',
    storageBucket: 'prochat-1d511.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEKPPCUaYvqquc-o9ysntMbt3E3AaYe4',
    appId: '1:687345271480:android:5d02f06315d2aaadbf2a4d',
    messagingSenderId: '687345271480',
    projectId: 'prochat-1d511',
    storageBucket: 'prochat-1d511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHeAuF1QOAsCVtnqJY0ZP3aN0-BFU_QxI',
    appId: '1:687345271480:ios:ac87f721e07fc000bf2a4d',
    messagingSenderId: '687345271480',
    projectId: 'prochat-1d511',
    storageBucket: 'prochat-1d511.firebasestorage.app',
    iosBundleId: 'com.example.prochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHeAuF1QOAsCVtnqJY0ZP3aN0-BFU_QxI',
    appId: '1:687345271480:ios:ac87f721e07fc000bf2a4d',
    messagingSenderId: '687345271480',
    projectId: 'prochat-1d511',
    storageBucket: 'prochat-1d511.firebasestorage.app',
    iosBundleId: 'com.example.prochat',
  );
}
